"""The application icon.

Generated by ``scripts/make_logo.py`` — a polymer backbone, which is what the
tool builds. These check the assets exist and that the loaders degrade
gracefully rather than crashing a startup when they don't.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from paaf.gui import branding


def test_every_declared_size_is_present():
    missing = [s for s in branding.SIZES
               if not (branding.ASSETS / f"paaf_{s}.png").exists()]
    assert not missing, f"missing icon sizes: {missing} (run scripts/make_logo.py)"


def test_icon_path_picks_the_nearest_available_size():
    assert branding.icon_path(32).name == "paaf_32.png"
    # An unavailable size falls back to the closest one instead of failing.
    assert branding.icon_path(999).name == "paaf_512.png"
    assert branding.icon_path(1).name == "paaf_16.png"


def test_icons_are_square_and_the_right_size():
    Image = pytest.importorskip("PIL.Image", reason="Pillow not installed")
    for s in branding.SIZES:
        im = Image.open(branding.ASSETS / f"paaf_{s}.png")
        assert im.size == (s, s)
        assert im.mode == "RGBA"          # transparent corners, not a white box


def test_icon_uses_the_design_tokens():
    """The mark must not drift from the UI palette."""
    Image = pytest.importorskip("PIL.Image", reason="Pillow not installed")
    from paaf.gui import tokens as T

    im = Image.open(branding.ASSETS / "paaf_256.png").convert("RGB")
    colours = {c for _, c in im.getcolors(maxcolors=1 << 16)}

    def near(target, tol=12):
        t = tuple(int(target[i:i + 2], 16) for i in (1, 3, 5))
        return any(all(abs(c[k] - t[k]) <= tol for k in range(3)) for c in colours)

    assert near(T.BG_CHROME), "plate is not the sidebar chrome colour"
    assert near(T.PRIMARY), "bonds are not the primary blue"


def test_loaders_survive_missing_assets(monkeypatch, tmp_path):
    """A partial checkout must not stop the app from starting."""
    monkeypatch.setattr(branding, "ASSETS", tmp_path / "nope")
    assert branding.icon_path(64) is None
    assert branding.logo_pixmap(24) is None
    # app_icon returns None (no sizes added) rather than raising.
    icon = branding.app_icon()
    assert icon is None or True


@pytest.mark.skipif(not (Path(__file__).parent.parent / "scripts" /
                         "make_logo.py").exists(),
                    reason="generator script not shipped")
def test_generator_script_is_available_to_regenerate():
    src = (Path(__file__).parent.parent / "scripts" / "make_logo.py").read_text()
    assert "def draw_icon" in src
