"""Tests for the reorganized pipeline: periodic table, DL_FIELD runner,
sidebar order.
"""
from __future__ import annotations

import pytest


# ============================================================ periodic table
def test_periodic_table_data_covers_all_118():
    """The periodic table dataset must contain every element from H (1) to
    Og (118) with sensible masses and non-empty categories."""
    from paaf.periodic_data import ELEMENTS, BY_SYMBOL
    Zs = {e.Z for e in ELEMENTS}
    assert Zs == set(range(1, 119))
    for sym in ("H", "C", "N", "O", "S", "P", "Cl", "Fe", "Cu", "Au", "U"):
        assert sym in BY_SYMBOL, f"element {sym} missing"
        assert BY_SYMBOL[sym].mass > 0
        assert BY_SYMBOL[sym].category


def test_periodic_table_category_colors_defined():
    from paaf.periodic_data import ELEMENTS, CATEGORY_COLORS
    for e in ELEMENTS:
        assert e.category in CATEGORY_COLORS, \
            f"category {e.category!r} missing color"


# ============================================================ DL_FIELD runner
def test_dl_ff_key_translation():
    from paaf.dlfield_runner import _dl_ff_key, DL_FF_KEYS
    for reg_key, dl_key in DL_FF_KEYS.items():
        assert _dl_ff_key(reg_key) == dl_key
    # Unknown key falls through unchanged
    assert _dl_ff_key("no_such_ff") == "no_such_ff"


def test_dlfield_control_file_layout(tmp_path):
    """Ensure the written .control file contains the required tags in the
    positions DL_FIELD expects."""
    from paaf.dlfield_runner import write_dlfield_control
    struct = tmp_path / "structure.xyz"; struct.write_text("1\n\nC 0 0 0\n")
    c = write_dlfield_control(
        tmp_path / "polymer.control", struct,
        ff_key="pcff", output_engine="lammps",
        box_ang=(60.0, 60.0, 60.0),
    )
    text = c.read_text()
    lines = text.splitlines()
    # First non-empty line is title
    assert "Generated by paaf" in lines[0]
    # Second line configures DL_POLY output
    assert "DL_POLY" in lines[1]
    # Third line configures secondary output
    assert "lammps" in lines[2]
    # FF name appears on the 5th line
    assert "pcff" in lines[4]
    # A structure beside the control file is referenced by BARE name —
    # dl_field runs with that directory as cwd, and its parser cannot read
    # absolute paths containing spaces.
    cfg = [l for l in text.splitlines() if "configuration file" in l][0]
    assert cfg.split("*")[0].strip() == struct.name
    # Box vector line contains 60.0
    assert "60.0" in text


def test_dlfield_binary_lookup_prefers_env(monkeypatch, tmp_path):
    from paaf.dlfield_runner import find_dl_field
    fake = tmp_path / "dl_field"; fake.write_text("#!/bin/sh\nexit 0\n")
    monkeypatch.setenv("DL_FIELD_EXE", str(fake))
    assert find_dl_field(None) == fake


# ============================================================ pipeline branch
def test_pipeline_returns_runner_field_via_ff_kind():
    """The pipeline result dict should carry a `runner` key reflecting the
    FF's kind ('dl_field' vs 'moltemplate'). Verify at least the field
    values map correctly via ff_registry entries."""
    from paaf.ff_registry import get_ff
    assert get_ff("pcff").kind == "dlfield"
    assert get_ff("oplsaa").kind == "moltemplate_native"
    assert get_ff("gaff").kind == "gaff"


# ============================================================ sidebar order
def test_gui_nav_order_puts_builder_first():
    """Import-safe (no display needed): NAV_ITEMS defines the workflow order."""
    try:
        from PyQt5.QtWidgets import QApplication  # noqa
    except Exception:
        pytest.skip("PyQt5 not available in this environment")
    from paaf.gui.main_window import NAV_ITEMS
    names = [n for n, _ in NAV_ITEMS]
    # The six-step pipeline, in order.
    assert names[:6] == [
        "Builder", "Chain", "Optimize", "Force field", "Box", "Export",
    ]
    # Independent tools stay out of the pipeline flow. (System builder is
    # parked for now; Layering holds its sidebar slot.)
    for tool in ("Layering", "Blend"):
        assert tool in names
        assert names.index(tool) >= 6
    # Parked tools stay out of the sidebar (code kept).
    assert "System builder" not in names
    assert "Reactions" not in names
    # The old standalone Monomers page is gone
    assert "Monomers" not in names
