"""Wrapper around the DL_FIELD executable.

DL_FIELD (STFC / C. W. Yong) reads a *control file* + a structure and writes
DL_POLY / LAMMPS / GROMACS topology and configuration files. When the user
selects a DL_FIELD-backed force field (PCFF, COMPASS, CVFF, CHARMM36,
GROMOS 54A7, OPLS 2005, AMBER GAFF, TraPPE-EH, OPLS-UA) we shell out to the
``dl_field`` binary instead of running moltemplate.

The tool works with either an explicit ``dl_field_dir`` (pointing to the
extracted DL_FIELD distribution, e.g. ``dl_f_4.13/``) or with ``dl_field``
already on PATH.

Two entry points:

- :func:`write_dlfield_control` — build a minimal ``.control`` file targeting
  a specific FF, structure and output engine (LAMMPS / GROMACS / DL_POLY).
- :func:`run_dlfield` — invoke the binary and return the produced files.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

from .logging_utils import get_logger

log = get_logger(__name__)


def _write_dl_f_path(path: Path, dl_home: Path, control_name: str) -> None:
    """Write a `dl_f_path` file DL_FIELD can consume from any working directory.

    DL_FIELD 4.x requires a plain-text file named `dl_f_path` in the process
    working directory. Its shipped copy uses paths *relative* to the DL_FIELD
    home directory (e.g. `library = lib/`). We regenerate it here with
    ABSOLUTE paths so `dl_field` doesn't care what cwd it was launched in.
    """
    lib = (Path(dl_home) / "lib").resolve()
    solvent = (Path(dl_home) / "solvent").resolve()
    lines = [
        "# dl_f_path generated by paaf for PAAF.",
        "# Absolute paths so dl_field works from any working directory.",
        "",
        "# paths",
        f"library = {lib}/",
        f"solvent = {solvent}/",
        f"output  = ./",
        "",
        "# Control file",
        f"control = {control_name}",
        "",
    ]
    path.write_text("\n".join(lines))


DL_FF_KEYS = {
    "pcff":          "pcff",
    "compass":       "compass",
    "cvff":          "cvff",
    "opls2005_dl":   "opls2005",
    "opls_ua":       "opls_ua",
    "trappe_eh":     "trappe_eh",
    "charmm36":      "charmm36",
    "amber_gaff":    "amber_gaff",
    "gromos_54a7":   "gromos54a7",
    "dreiding":      "dreiding",
}


def _dl_ff_key(registry_key: str) -> str:
    """Translate a ff_registry key into the exact string DL_FIELD expects.

    The scheme table is consulted first, because it carries the ``POTENTIAL``
    string read out of each ``.par`` file — which is what DL_FIELD matches
    against, case included. ``DL_FF_KEYS`` remains as an override for the
    handful of keys that predate the table.
    """
    from .dlfield_styles import dl_field_accepts, scheme_for

    if registry_key in DL_FF_KEYS:
        return DL_FF_KEYS[registry_key]
    scheme = scheme_for(registry_key)
    if scheme is None:
        return registry_key
    if not scheme.supported or not dl_field_accepts(scheme.dl_key):
        raise ValueError(
            f"{scheme.display} ships as {scheme.par} but DL_FIELD 4.13 has no "
            f"control-file key for it, so it cannot be selected. "
            f"{scheme.note}".strip())
    return scheme.dl_key


@dataclass
class DLFieldResult:
    return_code: int
    log: str
    output_dir: Path
    control_file: Path
    outputs: List[Path]


# ---------------------------------------------------------------- discovery
def find_dl_field(dl_field_dir: Optional[Path] = None) -> Optional[Path]:
    """Locate the ``dl_field`` executable.

    Preference order:
      1. ``$DL_FIELD_EXE`` env var.
      2. ``dl_field_dir/dl_field`` (as shipped by STFC).
      3. ``dl_field`` on PATH.
    """
    env = os.environ.get("DL_FIELD_EXE")
    if env and Path(env).exists():
        return Path(env)
    if dl_field_dir:
        candidate = Path(dl_field_dir) / "dl_field"
        if candidate.exists():
            return candidate
    onpath = shutil.which("dl_field")
    return Path(onpath) if onpath else None


# ---------------------------------------------------------------- control file
def write_dlfield_control(
    control_path: str | Path,
    structure_path: str | Path,
    ff_key: str,
    output_engine: str = "lammps",   # lammps | gromacs | none
    energy_unit: str = "kcal/mol",
    box_ang: Optional[tuple[float, float, float]] = None,
    generate_dl_poly: bool = True,
    verbosity: int = 1,
) -> Path:
    """Write a minimal ``.control`` file for DL_FIELD.

    Format matches the ``dl_field.control`` shipped with DL_FIELD 4.x. Any
    lines the user's real workflow needs (velocity, solvation, freezing,
    tethers) can be added by post-editing the file.
    """
    control_path = Path(control_path)
    control_path.parent.mkdir(parents=True, exist_ok=True)
    dlff = _dl_ff_key(ff_key)
    box = box_ang or (250.0, 250.0, 250.0)
    lines: List[str] = []
    lines.append("Control file title. Generated by paaf")
    lines.append(f"{int(generate_dl_poly)}        * Construct DL_POLY output files")
    lines.append(f"{output_engine}       * Secondary output files (gromacs, chemshell, or none)")
    lines.append(f"0        * Write user udff dl_field.udff (0 = off, 1 = on)")
    lines.append(f"{dlff} * Type of force field")
    lines.append(f"{energy_unit}  * Energy unit: kcal/mol, kJ/mol, eV, or K")
    lines.append(f"normal   * Conversion criteria (strict, normal, loose)")
    lines.append(f"1        * Bond type (0=default, 1=harmonic , 2=Morse)")
    lines.append(f"1        * Angle type (0=default, 1=harmonic, 2=harmonic cos)")
    lines.append(f"none * Include user-defined information")
    lines.append(f"{verbosity}       * Verbosity mode: 1 = on, 0 = off")
    # A structure sitting beside the control file is referenced by bare
    # name: dl_field runs with that directory as cwd, and its parser cannot
    # digest spaces in an absolute path.
    _sp = Path(structure_path).resolve()
    if _sp.parent == control_path.resolve().parent:
        lines.append(f"{_sp.name} * configuration file")
    else:
        lines.append(f"{_sp} * configuration file")
    lines.append(f"none     * Output file in PDB. Put 'none' if not needed")
    lines.append(f"0 0.1 mol/dm^3  15.0 * Solution Maker: on/off, density, unit, cutoff")
    lines.append(f"0        * Optimise FIELD output size, if possible? 1=yes  0=no")
    lines.append(f"2        * Atom display: 1 = DL_FIELD format. 2 = Standard format")
    lines.append(f"2        * Vdw display format: 1 = 12-6 format   2 = LJ format")
    lines.append(f"default  * Epsilon mixing rule (organic FF only)")
    lines.append(f"default  * Sigma mixing rule (organic FF only)")
    lines.append(f"1        * Epsilon mixing rule (inorganic FF only)")
    lines.append(f"2        * Sigma mixing rule (inorganic FF only)")
    lines.append(f"1        * Epsilon mixing rule (BETWEEN different FF)")
    lines.append(f"1        * Sigma mixing rule (BETWEEN different FF)")
    lines.append(f"0        * Display additional info for protein 1=Yes  0=No")
    lines.append(f"0        * Freeze atoms? 1 = Yes  0 = No")
    lines.append(f"0        * Tether atoms? 1 = Yes  0 = No")
    lines.append(f"0        * Constrain bonds? 1 = Yes  0 = No")
    lines.append(f"0        * Apply rigid body? 1 = Yes  0 = No")
    lines.append(f"1        * Periodic condition ? 0=no, other = box type")
    lines.append(f"{box[0]}  0.0  0.0  * Cell vector a (x, y, z)")
    lines.append(f"0.0  {box[1]}  0.0  * Cell vector b (x, y, z)")
    lines.append(f"0.0  0.0  {box[2]}  * Cell vector c (x, y, z)")
    lines.append("default   * 1-4 scaling for coulombic (put default or x)")
    lines.append("default   * 1-4 scaling for vdw (put default or x)")
    lines.append("0  300.0  * Include velocity? 1=yes, 0=no and scaling temperature")
    lines.append("1         * Position solute at origin? 1 = yes, 0=no")
    lines.append("none  1.9 default * Solvate model? none or specify solvent")
    lines.append("0  10.0   * Add counter ions? 1=yes, 0=no, minimum distance")
    lines.append("0         * Not use")
    lines.append("0         * Not use")
    lines.append("0         * Not use")
    lines.append("")
    lines.append("########################################################")
    lines.append("########################################################")
    control_path.write_text("\n".join(lines) + "\n")
    log.info("Wrote DL_FIELD control file %s (FF=%s, engine=%s)",
             control_path, dlff, output_engine)
    return control_path


# ---------------------------------------------------------------- run
def run_dlfield(
    structure_path: str | Path,
    ff_key: str,
    work_dir: str | Path,
    dl_field_dir: Optional[Path] = None,
    output_engine: str = "lammps",
    box_ang: Optional[tuple[float, float, float]] = None,
    control_name: str = "polymer.control",
) -> DLFieldResult:
    """Run ``dl_field`` on `structure_path` and collect the outputs.

    Parameters
    ----------
    structure_path : path
        The xyz/pdb/mol2 configuration to type.
    ff_key : str
        Registry key (pcff, compass, cvff, opls2005_dl, ...).
    work_dir : path
        Working directory. dl_field will create dlf_output1/ here.
    dl_field_dir : path, optional
        DL_FIELD distribution directory (dl_f_4.13/). Used both to locate the
        binary and — via cwd — to give dl_field access to its `lib/`.
    output_engine : "lammps" | "gromacs" | "none"
        Which auxiliary topology to emit alongside the DL_POLY FIELD file.

    Returns
    -------
    :class:`DLFieldResult` with return code, log, and list of produced files.
    """
    structure_path = Path(structure_path).resolve()
    work_dir = Path(work_dir).resolve()
    work_dir.mkdir(parents=True, exist_ok=True)
    # DL_FIELD's Fortran control-file parser reads the configuration path
    # only up to the first whitespace. A space (or other awkward character)
    # anywhere in the path yields "User configuration file format not
    # recognise." with no further hint. Rather than fail, copy the structure
    # into the work dir under a bland name and reference it locally — the
    # run's cwd is the work dir, so a bare filename always resolves.
    if re.search(r"[^A-Za-z0-9._/\\-]", str(structure_path)):
        local = work_dir / ("config" + structure_path.suffix)
        shutil.copy2(structure_path, local)
        log.info("Structure path contains characters DL_FIELD cannot parse; "
                 "copied to %s", local)
        structure_path = local
    exe = find_dl_field(dl_field_dir)
    if exe is None:
        raise RuntimeError(
            "dl_field executable not found. Set $DL_FIELD_EXE, pass "
            "dl_field_dir=..., or add dl_field to PATH. Distribution: "
            "https://www.ccp5.ac.uk/DL_FIELD "
            "(free registration)"
        )
    control = write_dlfield_control(
        work_dir / control_name, structure_path, ff_key,
        output_engine=output_engine, box_ang=box_ang,
    )

    # DL_FIELD requires a `dl_f_path` file in its working directory that tells
    # it where the lib/ and solvent/ folders live. The one shipped inside
    # dl_f_4.13/ uses relative paths (library = lib/) — but our cwd is the
    # user's project output folder, not the DL_FIELD home. Write a customised
    # dl_f_path here with ABSOLUTE paths so dl_field can find everything.
    dl_home = None
    if dl_field_dir:
        dl_home = Path(dl_field_dir).resolve()
    elif exe:
        dl_home = Path(exe).resolve().parent
    if dl_home:
        _write_dl_f_path(work_dir / "dl_f_path", dl_home, control.name)
        log.info("Wrote dl_f_path -> %s (lib=%s)", work_dir / "dl_f_path", dl_home / "lib")

    cmd = [str(exe), control.name]
    log.info("Running dl_field: %s (cwd=%s)", " ".join(cmd), work_dir)
    proc = subprocess.run(cmd, cwd=str(work_dir), capture_output=True, text=True)
    log_text = (proc.stdout or "") + "\n" + (proc.stderr or "")

    # Save the full log next to polymer.control so users can inspect it after
    # the run (especially useful when dl_field returns rc=0 but produces no
    # output — its silent atom-typing failures show up here).
    log_path = work_dir / "dl_field.log"
    try:
        log_path.write_text(
            "$ " + " ".join(cmd) + "\n(cwd=" + str(work_dir) + ")\n\n"
            + "----- STDOUT -----\n" + (proc.stdout or "") + "\n"
            + "----- STDERR -----\n" + (proc.stderr or "") + "\n"
        )
    except OSError:
        pass

    # dl_field typically drops its output into dlf_output1/
    outputs: List[Path] = []
    for pattern in ("dlf_output1/*", "*.dlp", "*.data", "*.gro", "*.top", "*.mdp"):
        outputs.extend(sorted(work_dir.glob(pattern)))
    return DLFieldResult(
        return_code=proc.returncode, log=log_text,
        output_dir=work_dir, control_file=control, outputs=outputs,
    )
