"""GROMACS output writer.

Produces:

- ``.gro``   coordinate file (native, no external deps)
- ``.mdp``   simulation parameter file (mirrors the LAMMPS run: ensemble,
             temperature, pressure, damping constants, multi-stage EM -> NVT
             -> NPT if requested)
- ``.top``   topology scaffold (native). Atoms / bonds / angles / dihedrals
             are emitted from the internal ``Molecule`` graph; the user must
             ``#include`` a GROMACS-native force-field ``.itp`` (OPLS-AA,
             GAFF, CHARMM36, etc.) — the tool prints the recommended include
             line as a comment at the top of the file.

Damping mapping (LAMMPS -> GROMACS):

    tdamp_fs -> tau_t (ps)         :  tau_t = tdamp_fs / 1000
    pdamp_fs -> tau_p (ps)         :  tau_p = pdamp_fs / 1000

    thermostat:  nose-hoover -> tcoupl = nose-hoover
                 langevin    -> tcoupl = v-rescale  (closest built-in)
                 berendsen   -> tcoupl = berendsen
                 csvr        -> tcoupl = v-rescale
    barostat:    nose-hoover -> pcoupl = Parrinello-Rahman
                 berendsen   -> pcoupl = Berendsen
                 parrinello  -> pcoupl = Parrinello-Rahman
    coupling:    iso/aniso/tri/... -> pcoupltype
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from .logging_utils import get_logger
from .structure import Molecule

log = get_logger(__name__)


# =============================================================== .gro
def write_gro(
    mol: Molecule,
    path: str | Path,
    box_ang: Optional[tuple[float, float, float]] = None,
    residue_name: str = "MOL",
    residue_number: int = 1,
) -> Path:
    """Write a GROMACS ``.gro`` coordinate file.

    Coordinates in the .gro file are in **nanometers**; we convert from Å.
    If ``box_ang`` is omitted, we use a cubic box big enough to bound the
    molecule + 10 Å padding on each side.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    coords = mol.coords()
    if box_ang is None:
        pad = 10.0
        lo = coords.min(axis=0); hi = coords.max(axis=0)
        box_ang = tuple(float((hi[i] - lo[i]) + 2 * pad) for i in range(3))
    box_nm = tuple(x * 0.1 for x in box_ang)

    lines: List[str] = []
    lines.append(f"Generated by paaf - {mol.name}")
    lines.append(f"{len(mol.atoms):5d}")
    # atom lines: 5-digit resnum, resname, atomname, atomnum, x y z (nm)
    for i, a in enumerate(mol.atoms, start=1):
        aname = (a.name or a.element)[:5]
        line = "{:>5d}{:<5s}{:>5s}{:>5d}{:8.3f}{:8.3f}{:8.3f}".format(
            residue_number, residue_name[:5], aname, i,
            a.xyz[0] * 0.1, a.xyz[1] * 0.1, a.xyz[2] * 0.1,
        )
        lines.append(line)
    lines.append("{:10.5f}{:10.5f}{:10.5f}".format(*box_nm))
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote GROMACS .gro %s  (%d atoms, box=%.2f x %.2f x %.2f nm)",
             path, len(mol.atoms), *box_nm)
    return path


# =============================================================== .top
def write_top(
    mol: Molecule,
    path: str | Path,
    include_itp: Optional[str] = None,
    ff_name: str = "OPLS-AA",
    residue_name: str = "MOL",
    nb_func: int = 1,
) -> Path:
    """Write a GROMACS ``.top`` topology from the internal Molecule graph.

    The atom types (``a.ff_type``) are used verbatim; the corresponding
    ``[ atomtypes ]`` / ``[ bondtypes ]`` etc. must live in an ``.itp`` file
    that the user provides via ``include_itp`` (e.g. ``forcefield.itp`` from
    a GROMACS FF distribution). A commented-out include line is always emitted
    so the file is self-documenting.

    Bond / angle / dihedral functional-form indices default to GROMACS-standard
    harmonic (``func=1``); users can post-edit if a custom form is required.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Enumerate angles and dihedrals from the bond graph.
    neigh: Dict[int, List[int]] = {i: [] for i in range(len(mol.atoms))}
    for i, j, _ in mol.bonds:
        neigh[i].append(j); neigh[j].append(i)
    angles: List[tuple[int, int, int]] = []
    for j in range(len(mol.atoms)):
        nbs = sorted(neigh[j])
        for a_i in range(len(nbs)):
            for b_i in range(a_i + 1, len(nbs)):
                angles.append((nbs[a_i], j, nbs[b_i]))
    dihedrals: List[tuple[int, int, int, int]] = []
    seen = set()
    for i, j, _ in mol.bonds:
        for a in neigh[i]:
            if a == j:
                continue
            for d in neigh[j]:
                if d in (i, a):
                    continue
                quad = (a, i, j, d) if (a, i, j, d) not in seen else None
                if quad and (d, j, i, a) not in seen:
                    dihedrals.append(quad)
                    seen.add(quad)

    lines: List[str] = []
    lines.append(f"; GROMACS topology generated by paaf")
    lines.append(f"; Molecule: {mol.name}   Force field target: {ff_name}")
    lines.append(";")
    lines.append("; IMPORTANT: include your GROMACS force-field .itp before running,")
    if include_itp:
        lines.append(f'#include "{include_itp}"')
    else:
        lines.append('; #include "oplsaa.ff/forcefield.itp"   ; edit to point to your FF')
    lines.append("")
    lines.append("[ defaults ]")
    lines.append("; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ")
    lines.append(f"  {nb_func}       3          yes        0.5      0.5")
    lines.append("")
    lines.append(f"[ moleculetype ]")
    lines.append(f"; Name    nrexcl")
    lines.append(f"{residue_name}   3")
    lines.append("")
    lines.append("[ atoms ]")
    lines.append(";   nr  type  resnr  residu  atom  cgnr  charge  mass")
    for k, a in enumerate(mol.atoms, start=1):
        atype = a.ff_type or a.element
        aname = (a.name or a.element)[:5]
        lines.append(f"  {k:>4d}  {atype:<5s}  1  {residue_name:<5s}  {aname:<4s}  {k:>4d}  {a.charge:>8.4f}  0.0")
    lines.append("")

    lines.append("[ bonds ]")
    lines.append(";  ai  aj  func   (b0, kb come from the included .itp)")
    for i, j, _ in mol.bonds:
        lines.append(f"  {i + 1:>4d}  {j + 1:>4d}  1")
    lines.append("")

    if angles:
        lines.append("[ angles ]")
        lines.append(";  ai  aj  ak  func")
        for a, b, c in angles:
            lines.append(f"  {a + 1:>4d}  {b + 1:>4d}  {c + 1:>4d}  1")
        lines.append("")

    if dihedrals:
        lines.append("[ dihedrals ]")
        lines.append(";  ai  aj  ak  al  func    (proper, RB/OPLS = 3)")
        for a, b, c, d in dihedrals:
            lines.append(f"  {a + 1:>4d}  {b + 1:>4d}  {c + 1:>4d}  {d + 1:>4d}  3")
        lines.append("")

    lines.append("[ system ]")
    lines.append(f"{mol.name}")
    lines.append("")
    lines.append("[ molecules ]")
    lines.append(f"{residue_name}   1")
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote GROMACS .top %s  (%d bonds, %d angles, %d dihedrals)",
             path, len(mol.bonds), len(angles), len(dihedrals))
    return path


# =============================================================== .mdp
_THERMOSTAT_MAP = {
    "nose-hoover": "nose-hoover",
    "langevin":    "v-rescale",   # closest GROMACS analogue
    "berendsen":   "berendsen",
    "csvr":        "v-rescale",
}
_BAROSTAT_MAP = {
    "nose-hoover": "Parrinello-Rahman",
    "berendsen":   "Berendsen",
    "parrinello":  "Parrinello-Rahman",
}
_COUPLING_MAP = {
    "iso":   "isotropic",
    "aniso": "anisotropic",
    "tri":   "anisotropic",
    "x":     "semiisotropic",
    "y":     "semiisotropic",
    "z":     "semiisotropic",
}


def _mdp_common(timestep_fs: float, temperature: float, tdamp_fs: float,
                thermostat: str, thermo_every: int, dump_every: int) -> List[str]:
    tau_t = max(tdamp_fs / 1000.0, 0.1)
    tcoupl = _THERMOSTAT_MAP.get(thermostat, "v-rescale")
    lines = [
        f"; Generated by paaf",
        f"integrator      = md",
        f"dt              = {timestep_fs / 1000.0}",
        f"nstxout         = {dump_every}",
        f"nstvout         = 0",
        f"nstfout         = 0",
        f"nstenergy       = {thermo_every}",
        f"nstlog          = {thermo_every}",
        f"nstxout-compressed = {dump_every}",
        f"cutoff-scheme   = Verlet",
        f"ns_type         = grid",
        f"nstlist         = 20",
        f"rlist           = 1.2",
        f"rcoulomb        = 1.2",
        f"rvdw            = 1.2",
        f"coulombtype     = PME",
        f"pme_order       = 4",
        f"fourierspacing  = 0.16",
        f"pbc             = xyz",
        f"tcoupl          = {tcoupl}",
        f"tc-grps         = System",
        f"tau_t           = {tau_t}",
        f"ref_t           = {temperature}",
    ]
    return lines


def write_mdp(
    out_dir: str | Path,
    ensemble: str = "npt",
    temperature: float = 300.0,
    pressure: float = 1.0,
    steps: int = 500_000,
    timestep_fs: float = 1.0,
    tdamp_fs: float = 100.0,
    pdamp_fs: float = 1000.0,
    thermostat: str = "nose-hoover",
    barostat: str = "nose-hoover",
    pressure_coupling: str = "iso",
    minimize: bool = True,
    multistage: bool = False,
    nvt_steps: int = 100_000,
    nvt_temperature: Optional[float] = None,
    npt_steps: int = 500_000,
    thermo_every: int = 1000,
    dump_every: int = 0,
    seed: int = 4928459,
) -> List[Path]:
    """Write one or more MDP files.

    - Single-stage mode (default): writes ``em.mdp`` (if ``minimize``) and
      ``run.mdp`` for the chosen ensemble.
    - Multi-stage mode: writes ``em.mdp``, ``nvt.mdp``, ``npt.mdp``.

    Returns the list of paths written, in run order.
    """
    out_dir = Path(out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    tau_p = max(pdamp_fs / 1000.0, 0.1)
    Tnvt = nvt_temperature if nvt_temperature is not None else temperature

    if minimize:
        em = out_dir / "em.mdp"
        em.write_text("\n".join([
            "; Energy minimization",
            "integrator      = steep",
            "emtol           = 1000.0",
            "emstep          = 0.01",
            "nsteps          = 50000",
            "cutoff-scheme   = Verlet",
            "rlist           = 1.2",
            "rcoulomb        = 1.2",
            "rvdw            = 1.2",
            "coulombtype     = PME",
            "pbc             = xyz",
        ]) + "\n")
        log.info("Wrote GROMACS MDP %s (energy minimization)", em)
        written.append(em)

    if multistage:
        # NVT
        nvt = out_dir / "nvt.mdp"
        L = _mdp_common(timestep_fs, Tnvt, tdamp_fs, thermostat, thermo_every, dump_every)
        L += [
            f"nsteps          = {nvt_steps}",
            f"gen_vel         = yes",
            f"gen_temp        = {Tnvt}",
            f"gen_seed        = {seed}",
            "pcoupl          = no",
        ]
        nvt.write_text("\n".join(L) + "\n")
        log.info("Wrote GROMACS MDP %s (NVT equilibration)", nvt)
        written.append(nvt)

        # NPT
        npt = out_dir / "npt.mdp"
        L = _mdp_common(timestep_fs, temperature, tdamp_fs, thermostat, thermo_every, dump_every)
        L += [
            f"nsteps          = {npt_steps}",
            f"gen_vel         = no",
            f"pcoupl          = {_BAROSTAT_MAP.get(barostat, 'Parrinello-Rahman')}",
            f"pcoupltype      = {_COUPLING_MAP.get(pressure_coupling, 'isotropic')}",
            f"tau_p           = {tau_p}",
            f"ref_p           = {pressure}",
            f"compressibility = 4.5e-5",
        ]
        npt.write_text("\n".join(L) + "\n")
        log.info("Wrote GROMACS MDP %s (NPT production)", npt)
        written.append(npt)
    else:
        run = out_dir / "run.mdp"
        L = _mdp_common(timestep_fs, temperature, tdamp_fs, thermostat, thermo_every, dump_every)
        L += [
            f"nsteps          = {steps}",
            f"gen_vel         = yes",
            f"gen_temp        = {temperature}",
            f"gen_seed        = {seed}",
        ]
        if ensemble.lower() == "npt":
            # This file both GENERATES velocities and couples pressure, which
            # is starting an unequilibrated system under a barostat.
            # Parrinello-Rahman is known-unstable there — grompp says so
            # ("this can be unstable for equilibration") and then refuses the
            # run outright because the warning counts against -maxwarn. So a
            # single-stage NPT with fresh velocities gets C-rescale, which is
            # a correct-ensemble barostat that is stable from a cold start.
            # The user's chosen barostat is honoured in multistage mode,
            # where NVT equilibration runs first and the NPT stage inherits
            # its velocities.
            chosen = _BAROSTAT_MAP.get(barostat, "Parrinello-Rahman")
            if chosen == "Parrinello-Rahman":
                L += ["; Parrinello-Rahman swapped for C-rescale because this",
                      "; single file starts from generated velocities. For",
                      "; Parrinello-Rahman proper, use multistage (NVT->NPT).",
                      "pcoupl          = C-rescale"]
            else:
                L += [f"pcoupl          = {chosen}"]
            L += [
                f"pcoupltype      = {_COUPLING_MAP.get(pressure_coupling, 'isotropic')}",
                f"tau_p           = {tau_p}",
                f"ref_p           = {pressure}",
                f"compressibility = 4.5e-5",
            ]
        elif ensemble.lower() == "nvt":
            L += ["pcoupl          = no"]
        else:  # nve
            L += ["pcoupl          = no", "tcoupl          = no"]
        run.write_text("\n".join(L) + "\n")
        log.info("Wrote GROMACS MDP %s (%s)", run, ensemble.upper())
        written.append(run)
    return written


# =============================================================== convenience
def write_all(
    mol: Molecule,
    out_dir: str | Path,
    project_name: str = "system",
    box_ang: Optional[tuple[float, float, float]] = None,
    include_itp: Optional[str] = None,
    ff_name: str = "OPLS-AA",
    **mdp_kwargs,
) -> dict:
    """Emit ``.gro`` + ``.top`` + one or more ``.mdp`` files.

    Returns a dict of ``{"gro": ..., "top": ..., "mdps": [...]}``.
    """
    out_dir = Path(out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    gro = write_gro(mol, out_dir / f"{project_name}.gro", box_ang=box_ang)
    top = write_top(mol, out_dir / f"{project_name}.top",
                    include_itp=include_itp, ff_name=ff_name)
    mdps = write_mdp(out_dir, **mdp_kwargs)
    return {"gro": str(gro), "top": str(top), "mdps": [str(p) for p in mdps]}
